[package]
name = "ethereum_transaction"
version = "0.1.0"
edition = "2021"

[dependencies]
web3 = "0.19.0"
tokio = { version = "1", features = ["full"] }
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
